# Use an official Node runtime as a parent image
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install OpenSSL
RUN apk add --no-cache openssl

# Install dependencies
RUN npm install

# Copy the current directory contents into the container
COPY . .

# Build the app for production
RUN npm run build

# Use an official NGINX image to serve the build
FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
